name: RELEASE

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          registry-url: https://registry.npmjs.org/
      - name: git config
        run: |
          git config user.name "${{github.actor}}"
          git config user.email "${{github.actor}}@users.noreply.github.com"
      - run: npm i
      - run: npm test
      - run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.AT }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
